#!/usr/bin/env python3
"""A2b · ReembedDriftStream 3-class SUBSET run (host-only, analysis-only).

Runs the **re-embed** (input-level pixel cross-fade) arm of the paired
fidelity experiment through the *existing* calibration loop. It is the
authorized follow-on to the merged pilot gates (PR #93): same selection
state, same contraction schedule, same engine/probe/floor/vote — the only
difference from the cache-linear arm is that drift is generated by pixel
interpolation + a fresh DINOv2 re-embed instead of a linear blend of cached
features (see ``results/issue_input_reembed_fidelity/SCOPE.md`` §3 and
``REEMBED_DRIFT_STREAM_DESIGN.md``).

The cache-linear anchor arm is *not* run here: it is stock
``benchmarks/calibration_probe.py --vision`` with the same flags, unchanged.

This driver is deliberately thin. It reuses, verbatim and unmodified:

  * ``ReembedDriftStream.from_extractor`` / ``.batch`` — the re-embed arm;
  * ``calibration_probe.run_policy`` — the per-policy continual loop;
  * ``calibration_probe.ALL_COLS`` — the shared ``per_probe.csv`` schema,

so ``analyze_calibration.py`` and ``heldout_abstention.py`` run on the output
with no changes. Geometry diagnostics (SCOPE §5: arc length / deviation-vs-c)
are **deferred to a later PR** and are intentionally absent here.

It does **not** touch ``forward()``, ``associative_core.py``, the detector, the
analyzers, ``VisionDriftStream``, ``ReembedDriftStream``, or
``calibration_probe.run_policy``. Raw DINOv2 outputs flow into the engine
(``ReembedDriftStream.batch`` returns raw features; the engine normalizes
internally); unit-normalization appears only inside the existing pilot gates.

Host-only: requires the ImageNet-R dataset, the DINOv2 ViT-L/14 weights, and the
feature cache the extractor wrote. Nothing heavy is imported or loaded at module
import time — the model, extractor dataset, and cache are touched only inside
``main()``.
"""
import argparse
import csv
import json
import socket
import sys
from pathlib import Path

import torch

# Repo root for ``associative_core`` / ``dynamic_vigilance`` (pulled in by
# calibration_probe), and the benchmarks dir for the stream modules + extractor
# — mirrors probe_reembed_pilot.py's path setup.
sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent / "benchmarks"))


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    # --- subset selection (defaults pinned to the authorized 3-class run) ---
    ap.add_argument("--split", default="train", choices=["train", "test"])
    ap.add_argument("--vision-classes", type=str, default="166,63,77",
                    help="comma-separated cached class ids (deterministic "
                         "first-three subset of #88's {166,63,77,156})")
    ap.add_argument("--vision-attractor-class", type=int, default=134,
                    help="shared attractor class blended into every class")
    ap.add_argument("--vision-cache", type=str,
                    default="feature_cache_inr_vitl14/imagenetr_dinov2_train.pt",
                    help="path to the *_train.pt ImageNet-R ViT-L/14 cache")
    ap.add_argument("--samples-per-class", type=int, default=32)
    ap.add_argument("--held-out-per-class", type=int, default=64)
    ap.add_argument("--seed", type=int, default=0)
    # --- schedule (identical formula + bounds to calibration_probe.main) ---
    ap.add_argument("--epochs", type=int, default=30)
    ap.add_argument("--contraction-start", type=float, default=0.35)
    ap.add_argument("--contraction-end", type=float, default=0.9)
    ap.add_argument("--policies", type=str, default="margin,relative",
                    help="comma-separated vigilance policies (forwarded to "
                         "run_policy)")
    # --- pilot-gate re-check (asserted at subset scale before the run) ---
    ap.add_argument("--gate-contractions", type=str, default="0.25,0.5,0.75",
                    help="mid-path c values for the G2 divergence re-check")
    # --- engine / vigilance / floor params consumed by run_policy verbatim,
    #     defaulted to the merged #83/#84/#88 values ---
    ap.add_argument("--max-entries", type=int, default=4096)
    ap.add_argument("--blend-eps", type=float, default=0.10)
    ap.add_argument("--v-base", type=float, default=0.92)
    ap.add_argument("--alpha", type=float, default=0.30)
    ap.add_argument("--v-floor", type=float, default=0.30)
    ap.add_argument("--v-ceiling", type=float, default=0.95)
    ap.add_argument("--margin-guard", type=float, default=0.05)
    ap.add_argument("--percentile", type=float, default=0.95)
    ap.add_argument("--k-logit-steps", type=float, default=3.0)
    ap.add_argument("--floor-ema-beta", type=float, default=0.9)
    ap.add_argument("--out", type=str,
                    default="results/issue_input_reembed_fidelity/per_probe_reembed.csv")
    args = ap.parse_args()

    vcats = [int(c.strip()) for c in args.vision_classes.split(",") if c.strip()]
    if args.vision_attractor_class in vcats:
        ap.error("--vision-attractor-class must not be one of --vision-classes")
    policies = [p.strip() for p in args.policies.split(",") if p.strip()]
    gate_contractions = tuple(
        float(x) for x in args.gate_contractions.split(",") if x.strip())

    # Lazy imports: stream modules + extractor + the reused calibration loop.
    # None of these load a model/dataset/cache at import time.
    import extract_imagenet_r_vitl14 as ex            # noqa: E402
    from probe_contraction import VisionDriftStream    # noqa: E402
    from reembed_drift_stream import (                 # noqa: E402
        G1_COS_THRESHOLD, G2_MIN_DIVERGENCE, ReembedDriftStream, pilot_verdict)
    from calibration_probe import run_policy, ALL_COLS  # noqa: E402

    host = socket.gethostname()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[subset] host={host} device={device} classes={vcats} "
          f"attractor={args.vision_attractor_class}")

    # 1. Cache-linear selection state — identical to the anchor arm. The
    #    re-embed arm consumes this verbatim; it never re-derives selection.
    vision = VisionDriftStream(
        categories=vcats, attractor_category=args.vision_attractor_class,
        samples_per_class=args.samples_per_class,
        held_out_per_class=args.held_out_per_class,
        seed=args.seed, cache_path=args.vision_cache)
    num_classes, dim = vision.num_classes, vision.dim
    print(f"[subset] cache={vision.cache_path} dim={dim}")

    # 2. Live DINOv2 ViT-L/14 + the input-level arm (same selection, pixels).
    print("[subset] loading DINOv2 ViT-L/14 ...")
    model = torch.hub.load("facebookresearch/dinov2", "dinov2_vitl14")
    reembed = ReembedDriftStream.from_extractor(
        vision, ex, model, device=device, split=args.split)

    # 2a. Re-assert the pilot gates at subset scale BEFORE calibrating. A
    #     non-PASS verdict aborts with a nonzero exit so no automation can
    #     mistake a broken pairing / collinear path for a green light.
    verdict = pilot_verdict(reembed, vision, contractions=gate_contractions)
    print(json.dumps({
        "verdict": verdict["verdict"], "gate": verdict["gate"],
        "reason": verdict["reason"], "parity": verdict["parity"],
        "g1_min_cosine": verdict["g1_min_cosine"],
        "g1_threshold": G1_COS_THRESHOLD,
        "g2_divergence_per_c": verdict["g2_divergence"],
        "g2_min_divergence": G2_MIN_DIVERGENCE,
    }, indent=2))
    if verdict["verdict"] != "PASS":
        print(f"[subset] gate re-check {verdict['verdict']} "
              f"(gate={verdict['gate']}); refusing to run the subset.",
              file=sys.stderr)
        sys.exit(1)

    # 3. Precompute the epoch batches from the RE-EMBED arm. Same schedule
    #    math as calibration_probe.main(); raw DINOv2 features into the engine.
    print(f"[subset] precomputing {args.epochs} re-embed epoch batches "
          f"(c: {args.contraction_start}->{args.contraction_end}) ...")
    batches = []
    for epoch in range(args.epochs):
        frac = epoch / (args.epochs - 1) if args.epochs > 1 else 0.0
        contraction = args.contraction_start + frac * (
            args.contraction_end - args.contraction_start)
        (q, y, lab), (hq, hlab) = reembed.batch(contraction)
        batches.append((contraction, q, y, lab, hq, hlab))
    print(f"[subset] done ({sum(b[1].size(0) + b[4].size(0) for b in batches)} "
          f"re-embeds)")

    # 4. Reuse the engine loop verbatim, one pass per vigilance policy, writing
    #    the shared per_probe schema.
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    total = 0
    with open(out_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=ALL_COLS)
        writer.writeheader()
        for pol in policies:
            print(f"\n=== vigilance policy: {pol} (re-embed arm) ===")
            total += run_policy(pol, batches, num_classes, dim, args, writer)
    print(f"\nWrote {total} per-probe rows to {out_path}")


if __name__ == "__main__":
    main()
